### ISSUE TITLE
Problem Respawn at Checkpoints

### ISSUE THREAD

**Issue by Anfournier** [VroumStudio/REKT#15]
- The Vehicle goes in the ground after respawn sometime.

- The Vehicle keep its inertia & velocity after respawning, becoming unctontrollable.

**Comment by tbeaugelin** [comment]
Update: fond this wich can be helpfull.
https://api.unrealengine.com/INT/BlueprintAPI/Components/SkeletalMesh/ResetAllBodiesSimulatePhysics/index.html

**Comment by tbeaugelin** [comment]
Update: could also work with this, if above method does not work.
https://api.unrealengine.com/INT/BlueprintAPI/Physics/SetAllPhysicsLinearVelocity/index.html

**Comment by tbeaugelin** [comment]
Update: Respawn now completly functional.
