### ISSUE TITLE
Minions Crush

### ISSUE THREAD

**Issue by Anfournier** [VroumStudio/REKT#29]
Certains minions ne sont pas écrasables (les plus rapides il me semble).

**Comment by tbeaugelin** [comment]
They are crushable. Problem is the Capsule component is not scaled properly compared to the used mesh.

**Comment by Anfournier** [comment]
Okay. If it's something easy to correct, can you correct it please ? It's quite frustrating sometime...

**Comment by tbeaugelin** [comment]
Issue has been corrected, but there seems to be some inconsistent behavior. Needs further investigation.

**Comment by tbeaugelin** [comment]
Issue fixed. Marking as closed.
