### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by Anfournier** [VroumStudio/REKT#30]
- Les onglets disparaissent parfois ou se superposent.

- La voiture est contrôlable dans le menu (x3 boost = drôle).

**Comment by tbeaugelin** [comment]
Is it still not working properly ? A fix should have been implemented in commit 1e37fd6b591fe9a7e3ca51aac82aadd469896708, in date of Feb. 27 2019, 11:06AM.
More information is wanted.

**Comment by Anfournier** [comment]
May be a new bug appears when I try to check : from the editor, I launch the game, I pause it to go back in main menu and arrive in the garage, but none of the widgets appears and we can do nothing (we just see the back of the car, in the garage).

Then I check in the map "Menu_Persistent" and it's much better ! Good work !

Questions :
1 - Is it controllable with a controller soon to test it ?
2 - The focus on the buttons is quite difficult and seems very precise. Is it possible to enlarge the box detection buttons or something like that ?
3 - Can you put the "Back" button in the other corner (bottom right) and make it bigger (with an indication of the input needed, normally "B" button in the XBox Controller) ?

**Comment by tbeaugelin** [comment]
1 has been done recently
2 has been changed recently (the text were causing a lost of focus on the button. No longer happens)
Problem solved, making as closed.
