### ISSUE TITLE
Car stuck at start

### ISSUE THREAD

**Issue by Anfournier** [VroumStudio/REKT#40]
When launching babypark through the main menu (editor play), the car does not move anymore.

EDIT: rewritten in En, added additional details.

**Comment by tbeaugelin** [comment]
- Does the issue happens when in editor ? Known Glitch, can't be fixed.
- Does the issue happens when in build ? This is a glitch, and it must be fixes.

**Comment by tbeaugelin** [comment]
Simple check: open level Babypark_Persistent. If you can play, there will be no probleme once the project is built.

**Comment by Anfournier** [comment]
No problem then. Will be fix by launching through build. Thx !
