### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by Anfournier** [VroumStudio/REKT#46]
When I press "A" input during the loading screen, the video of the keys mapping restart.

**Comment by tbeaugelin** [comment]
It might come from the fact that the start of the sequence is bound to the OnClick of A Input. I need to find another method, to unbound it from this event.

**Comment by tbeaugelin** [comment]
Problem have been fixed with a DoOnce for the OnClicked of 'A'. Marking as closed.
